<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\factory_dashboard.png" />
    <None Remove="backend\create_purchase_contract.py" />
    <None Remove="backend\database_config.json" />
    <None Remove="backend\update_purchase_contract.py" />
    <None Remove="Images\applogo.ico" />
    <None Remove="Images\Rubex_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="backend\create_purchase_contract.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="backend\database_config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="backend\read_purchase_contract.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="backend\update_purchase_contract.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\factory_dashboard.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\applogo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Rubex_logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
